### ISSUE TITLE
nbsp checking for local attrs no longer needed

### ISSUE THREAD

**Issue by soulcharmer** [Levi-Leah/enki#3]
"ERROR: {nsbp} attribute ... "  should no longer apply to local attr files

We added 

:nbsp: &nbsp;

at the top of the global attr file instead.

**Comment by soulcharmer** [comment]
For the record, it didn't work as expected :-X

Neither did :nbsp: &#160;

So the issue now is how to make nbsps work with Jup..

**Comment by Levi-Leah** [comment]
check was removed
