### ISSUE TITLE
list of tests from pcmd we might no longer need

### ISSUE THREAD

**Issue by soulcharmer** [Levi-Leah/enki#5]
ERROR: toc attribute found in the following files:

ERROR: `{nsbp}` attribute is used but not defined. `:nbsp: &nbsp` attribute is not found in the following files: 
See issue #1 

ERROR: HTML markup found in the following files:
Thus far does not report anything ilegitimate - might need some refining if HTML snippets need a wrapper or something

ERROR: empty line after the abstract tag found in the following files:

ERROR: empty line before the abstract tag not found in the following files:

ERROR: an empty line after the additional resources header was found in the following files:

ERROR: an empty line after the additional resources tag was found in the following files:

**Comment by Levi-Leah** [comment]
experimental tag gets inherited so the corresponding test can be removed
